### ISSUE TITLE
Exception at multicam_mapper.cpp:970 with OpenCV 3.4

### ISSUE THREAD

**Issue by Lukaviy** [HSarham/automatic-ar#1]
Hi! Thanks for your great work!

I just cloned your repo, bult it (with some minor fixes), and run it with example data from Readme.
I used OpenCV 3.4 - commit sha [eab7faf536eea224863195e15b7ae9bf491745a3](https://github.com/opencv/opencv/commit/eab7faf536eea224863195e15b7ae9bf491745a3)

And when I run this command:
```code
find_solution box 0.05
```

I get an exception at `multicam_mapper.cpp:970`:
![image](https://user-images.githubusercontent.com/3991095/211308831-e59c99ca-f60b-4a47-ae70-b5613328bb28.png)
That's because the last range is denoted as `[3, 3)` which means that range is empty[[cv::Range](https://docs.opencv.org/3.4/da/d35/classcv_1_1Range.html)]. So `copyTo()` function fails to copy to empty range.

Also, I built your project with OpenCV 3.2 - commit sha [70bbf17b133496bd7d54d034b0f94bd869e0e810](https://github.com/opencv/opencv/commit/70bbf17b133496bd7d54d034b0f94bd869e0e810)

And yeah, there isn't any exception thrown, but `copyTo()` function just does nothing:
![image](https://user-images.githubusercontent.com/3991095/211310157-f33ba745-72a3-431f-9b3a-3559cca7fef6.png)

So else branch can be thrown away without any visible consequences:
![image](https://user-images.githubusercontent.com/3991095/211312085-972daa26-0024-4c35-a1a8-fbdcf4703964.png)
Which doesn't seem right.

As I can see in the comment, this code is supposed to revert changes made previously here:
![image](https://user-images.githubusercontent.com/3991095/211322021-3c3097e1-88f6-47be-8e2b-8c09848f19c9.png)
When `i > 3` column `3` were modified, therefore we need to restore column range `[3, 4)`.

![image](https://user-images.githubusercontent.com/3991095/211322910-21f13d3e-7857-4e7e-867d-ab106d4691af.png)
After that, minimization converges much faster. 
Before:
![image](https://user-images.githubusercontent.com/3991095/211323154-8ac812ea-216d-4472-8e2c-130a60e7b0d4.png)
And after:
![image](https://user-images.githubusercontent.com/3991095/211323533-ee5df416-f6d0-4e84-b743-18ed1029876b.png)

Difference between results (new on the right):
![image](https://user-images.githubusercontent.com/3991095/211324466-7a8448c0-9166-4f04-87a7-6ab92c42e332.png)

[final.solution.txt](https://github.com/HSarham/automatic-ar/files/10373729/final.solution.txt)
[final.solution — new.txt](https://github.com/HSarham/automatic-ar/files/10373718/final.solution.new.txt)

I haven't yet understood what's going on here, I wanted to start just by running examples first. So I can't really tell how to fix it or whether it does need fixing. Just wanted to let you know what I've encountered. 
Thanks again!

**Comment by HSarham** [comment]
I think you've found a bug. Thanks for reporting. As you've noticed the column range is supposed to be Range(3,4) which refers to the last column of the transformation. It is now fixed in the master branch.
